In [1]:
import geopandas as gpd
import pandas as pd
import matplotlib
pd.set_option('display.max_columns', 500)
countries = gpd.read_file('../data/ne_10m_admin_0_countries/ne_10m_admin_0_countries.shp')
cities = gpd.read_file('../data/ne_10m_populated_places/ne_10m_populated_places.shp')
rivers  = gpd.read_file('../data/rivers.geojson')

## 1. Mapping single layer

In [2]:
# Visualising single dataframe
countries.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [3]:
#Convert into EPSG:3857 which has unit of m
countries = countries.to_crs(3857)

In [ ]:
countries

In [ ]:
countries.plot(column='CONTINENT')

In [6]:
# remove
countries = countries[countries.NAME!="Antarctica"]

In [ ]:
countries.plot(column='CONTINENT')

In [ ]:
# with legend
import matplotlib.pyplot as plt

fig, ax = plt.subplots(1, 1)

countries.plot(column='CONTINENT', ax=ax, legend=True)

In [ ]:

countries.plot(column='CONTINENT',  cmap='OrRd')
#Checkout available color maps => https://matplotlib.org/2.0.2/users/colormaps.html

## 2. Creating visualization of multiple layers

In [ ]:
basemap = countries.plot(column='CONTINENT', cmap='cool')
cities = cities.to_crs(3857)
cities.plot(ax=basemap, marker='o', color='red', markersize=5)

In [10]:
bbox = gpd.read_file('../data/world.geojson')

In [ ]:
world = bbox.loc[0].geometry
world

In [12]:
accepted_cities = cities[cities.within(world)]

In [ ]:
basemap = countries.plot(column='CONTINENT', cmap='cool')
cities = cities.to_crs(3857)
accepted_cities.plot(ax=basemap, marker='o', color='red', markersize=2)

## 3. Creating visualization based on overlay data

e.g. - find out all rural areas in India (Indian geometry which is not within 50KM of city point

In [14]:
India = countries[countries['NAME'] == 'India']
India

,featurecla,scalerank,LABELRANK,SOVEREIGNT,SOV_A3,ADM0_DIF,LEVEL,TYPE,ADMIN,ADM0_A3,GEOU_DIF,GEOUNIT,GU_A3,SU_DIF,SUBUNIT,SU_A3,BRK_DIFF,NAME,NAME_LONG,BRK_A3,BRK_NAME,BRK_GROUP,ABBREV,POSTAL,FORMAL_EN,FORMAL_FR,NAME_CIAWF,NOTE_ADM0,NOTE_BRK,NAME_SORT,NAME_ALT,MAPCOLOR7,MAPCOLOR8,MAPCOLOR9,MAPCOLOR13,POP_EST,POP_RANK,GDP_MD_EST,POP_YEAR,LASTCENSUS,GDP_YEAR,ECONOMY,INCOME_GRP,WIKIPEDIA,FIPS_10_,ISO_A2,ISO_A3,ISO_A3_EH,ISO_N3,UN_A3,WB_A2,WB_A3,WOE_ID,WOE_ID_EH,WOE_NOTE,ADM0_A3_IS,ADM0_A3_US,ADM0_A3_UN,ADM0_A3_WB,CONTINENT,REGION_UN,SUBREGION,REGION_WB,NAME_LEN,LONG_LEN,ABBREV_LEN,TINY,HOMEPART,MIN_ZOOM,MIN_LABEL,MAX_LABEL,NE_ID,WIKIDATAID,NAME_AR,NAME_BN,NAME_DE,NAME_EN,NAME_ES,NAME_FR,NAME_EL,NAME_HI,NAME_HU,NAME_ID,NAME_IT,NAME_JA,NAME_KO,NAME_NL,NAME_PL,NAME_PT,NAME_RU,NAME_SV,NAME_TR,NAME_VI,NAME_ZH,geometry
8,Admin-0 country,0,2,India,IND,0,2,Sovereign country,India,IND,0,India,IND,0,India,IND,0,India,India,IND,India,None,India,IND,Republic of India,None,India,None,None,India,None,1,3,2,2,1281935911,18,8721000.0,2017,2011,2016,3. Emerging region: BRIC,4. Lower middle income,-99,IN,IN,IND,IND,356,356,IN,IND,23424848,23424848,Exact WOE match as country,IND,IND,-99,-99,Asia,Asia,Southern Asia,South Asia,5,5,5,-99,1,0.0,1.7,6.7,1159320847,Q668,الهند,ভারত,Indien,India,India,Inde,Ινδία,भारत,India,India,India,インド,인도,India,Indie,Índia,Индия,Indien,Hindistan,Ấn Độ,印度,"MULTIPOLYGON (((8660694.935 4231410.254, 86623..."

In [15]:
Indian_cities = cities[cities.within(India.iloc[0].geometry)]

In [16]:
Indian_cities

,SCALERANK,NATSCALE,LABELRANK,FEATURECLA,NAME,NAMEPAR,NAMEALT,DIFFASCII,NAMEASCII,ADM0CAP,CAPIN,WORLDCITY,MEGACITY,SOV0NAME,SOV_A3,ADM0NAME,ADM0_A3,ADM1NAME,ISO_A2,NOTE,LATITUDE,LONGITUDE,CHANGED,NAMEDIFF,DIFFNOTE,POP_MAX,POP_MIN,POP_OTHER,RANK_MAX,RANK_MIN,GEONAMEID,MEGANAME,LS_NAME,LS_MATCH,CHECKME,MAX_POP10,MAX_POP20,MAX_POP50,MAX_POP300,MAX_POP310,MAX_NATSCA,MIN_AREAKM,MAX_AREAKM,MIN_AREAMI,MAX_AREAMI,MIN_PERKM,MAX_PERKM,MIN_PERMI,MAX_PERMI,MIN_BBXMIN,MAX_BBXMIN,MIN_BBXMAX,MAX_BBXMAX,MIN_BBYMIN,MAX_BBYMIN,MIN_BBYMAX,MAX_BBYMAX,MEAN_BBXC,MEAN_BBYC,COMPARE,GN_ASCII,FEATURE_CL,FEATURE_CO,ADMIN1_COD,GN_POP,ELEVATION,GTOPO30,TIMEZONE,GEONAMESNO,UN_FID,UN_ADM0,UN_LAT,UN_LONG,POP1950,POP1955,POP1960,POP1965,POP1970,POP1975,POP1980,POP1985,POP1990,POP1995,POP2000,POP2005,POP2010,POP2015,POP2020,POP2025,POP2050,CITYALT,min_zoom,wikidataid,wof_id,CAPALT,name_en,name_de,name_es,name_fr,name_pt,name_ru,name_zh,label,name_ar,name_bn,name_el,name_hi,name_hu,name_id,name_it,name_ja,name_ko,name_nl,name_pl,name_sv,name_tr,name_vi,wdid_score,ne_id,geometry
560,9,5,1,Admin-1 capital,Panaji,None,None,0,Panaji,0.0,None,0.0,0,India,IND,India,IND,Goa,IN,None,15.491997,73.818001,4.0,1,Added missing admin-1 capital. Population from...,65586,65586,0,8,8,1260607.0,None,None,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0,Panaji,P,PPLA,33.0,65586.0,0.0,6.0,Asia/Kolkata,GeoNames match general.,0,None,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,7.0,Q214681,102029109,0,Panjim,Panaji,Panaji,Panaji,Pangim,Панаджи,帕纳吉,None,بانجيم,পানাজি,Πάντζιμ,पणजी,Panadzsi,Panaji,Panaji,パナジ,파나지,Panaji,Panaji,Panaji,Panaji,Panaji,4,1159122667,POINT (8217382.244 1745967.061)
1352,8,10,1,Admin-1 capital,Simla,None,Shimla,0,Simla,0.0,None,0.0,0,India,IND,India,IND,Himachal Pradesh,IN,None,31.100025,77.166597,1.0,1,Added place. Population from GeoNames.,173503,173503,0,9,9,1256237.0,None,None,2,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1,Shimla,P,PPLA,11.0,173503.0,0.0,1959.0,Asia/Kolkata,GeoNames match general.,0,None,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,7.0,Q83786,102028631,0,Shimla,Shimla,Shimla,Shimla,Shimla,Шимла,西姆拉,None,شيملا,শিমলা,Σίμλα,शिमला,Simlá,Shimla,Shimla,シムラー,심라,Shimla,Shimla,Shimla,Shimla,Shimla,4,1159130425,POINT (8590146.289 3645746.177)
1353,8,10,1,Populated place,Gurgaon,None,None,0,Gurgaon,0.0,None,0.0,0,India,IND,India,IND,Haryana,IN,None,28.450006,77.019991,0.0,0,None,197340,197340,3212622,9,9,1270642.0,None,Gurgaon,1,0,3377995.0,0.0,0.0,0.0,0.0,10.0,3440.0,3440.0,1328.0,1328.0,2493.0,2493.0,1549.0,1549.0,76.425466,76.425466,77.420882,77.420882,27.842258,27.842258,28.725019,28.725019,76.973246,28.279999,0,Gurgaon,P,PPL,10.0,197340.0,0.0,216.0,Asia/Kolkata,Geonames ascii name + lat.d + long.d matching.,0,None,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,7.0,Q238508,102030161,0,Gurgaon,Gurgaon,Gurgaon,Gurgaon,Gurgaon,Гургаон,古爾岡,None,جورجاون,গুড়গাঁও,Γκούργκαον,गुडगाँव,Gurgáon,Gurgaon,Gurgaon,グルガーオン,구르가온,Gurgaon,Gurgaon,Gurgaon,Gurgaon,Gurgaon,4,1159130429,POINT (8573826.180 3305828.675)
1354,8,10,1,Populated place,Sonipat,None,None,0,Sonipat,0.0,None,0.0,0,India,IND,India,IND,Haryana,IN,None,28.999999,77.019991,0.0,0,None,250521,250521,1711294,10,10,1255744.0,None,Sonipat,1,0,1788816.0,0.0,0.0,0.0,0.0,10.0,1801.0,1801.0,695.0,695.0,983.0,983.0,611.0,611.0,76.750755,76.750755,77.359985,77.359985,28.725019,28.725019,29.245120,29.245120,77.074304,29.010539,0,Sonipat,P,PPL,10.0,250521.0,0.0,220.0,Asia/Kolkata,Geonames ascii name + lat.d + long.d matching.,0,None,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,7.0,Q41561,102028575,0,Sonipat,Sonipat,Sonipat,Sonipat,Sonipat,Сонипат,索尼帕特,None,سونيبات,সোনিপাত,None,सोनीपत,Sonipat,None,Sonipat,ソーニーパト,소니파트,Sonipat,Sonipat,Sonipat,Sonipat,Sonipat,4,1159130433,POINT (8573826.180 3375645.856)
1355,8,10,1,Populated place,Rohtak,None,None,0,Rohtak,0.0,None,0.0,0,India,IND,India,IND,Haryana,IN,None,28.900005,76.580018,0.0,0,None,317245,317245,1708277,10,10,1258076.0,None,Rohtak,1,0,1758925.0,0.0,0.0,0.0,0.0,10.0,1953.0,1953.0,754.0,754.0,2432.0,2432.0,1511.0,1511.0,76.253592,76.253592,76.851129,76.851129,28.337565,28.337565,29.466667,29.466667,76.550597,28.935213,0,Rohtak,P,PPL,10.0,317245.0,0.0,214.0,Asia/Kolkata,Geonames ascii name + lat.d + long.d matching.,0,None,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,7.0,Q1453180,102028805,0,Rohtak,Rohtak,Rohtak,Rohtak,Rohtak,Рохтак,罗赫塔克,None,روهتاك,রোহতক,Ρόχτακ,रोहतक,None,Rohtak,Rohtak,ロータク,롯탁,Rohtak,Rohtak,Rohtak,Rohtak,Rohtak,4,1159130437,POINT (8524848.593 3362925.019)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7202,2,200,1,Populated place,Surat,None,None,0,Surat,0.0,None,0.0,1,India,IND,India,IND,Dadra and Nagar Haveli,IN,None,21.199984,72.840039,5.0,0,Changed scale rank.,3842000,2894504,4117672,12,12,1255364.0,Surat,Surat,1,0,4333141.0,4355597.0,5051432.0,5051432.0,0.0,100.0,1589.0,2121.0,613.0,819.0,1261.0,1767.0,784.0,1098.0,72.641667,72.641667,73.341667,73.358333,20.833333,21.014327,21.758333,21.816667,72.974945,21.266132,0,Surat,P,PPL,9.0,2894504.0,0.0,13.0,Asia/Kolkata,Geonames ascii name + lat.d + long.d matching.,265,India,21.16,72.83,234.0,269.0,311.0,384.0,477.0,642.0,877.0,1139.0,1468.0,1984.0,2699.0,3558.0,3842.0,4174.0,4639.0,5142.0,5703.0,None,4.0,Q4629,102028539,0,Surat,Surat,Surat,Surate,Surate,Сурат,苏拉特,None,سورات,সুরাট,Σουράτ,सूरत,Szúrat,Surat,Surat,スーラト,수라트,Surat,Surat,Surat,Surat,Surat,4,1159151435,POINT (8108299.486 2415972.887)
7249,1,300,1,Admin-0 capital,New Delhi,None,None,0,New Delhi,1.0,None,1.0,0,India,IND,India,IND,Delhi,IN,None,28.600023,77.199980,0.0,0,None,317797,317797,8060107,10,10,1261481.0,None,New Delhi,1,0,8761047.0,13414375.0,32426336.0,32424761.0,224908923.0,300.0,864.0,186559.0,334.0,72030.0,244.0,130296.0,152.0,80962.0,71.033333,76.943289,77.431830,82.566667,24.000000,28.152007,28.738629,33.466667,77.272945,28.382537,0,New Delhi,P,PPLC,7.0,317797.0,0.0,205.0,Asia/Kolkata,GeoNames match general.,0,None,0.00,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,None,2.1,Q987,102029189,0,New Delhi,Neu-Delhi,Nueva Delhi,New Delhi,Nova Deli,Нью-Дели,新德里,None,نيودلهي,নয়াদিল্লি,Νέο Δελχί,नई दिल्‍ली,Új-Delhi,New Delhi,Nuova Delhi,ニューデリー,뉴델리,New Delhi,Nowe Delhi,New Delhi,Yeni Delhi,New Delhi,4,1159151541,POINT (8593862.465 3324835.758)
7250,1,300,1,Admin-1 capital,Bangalore,None,Bengaluru,0,Bangalore,0.0,None,0.0,1,India,IND,India,IND,Karnataka,IN,None,12.969995,77.560010,3.0,1,Name changed. Changed scale rank.,6787000,5104047,8102712,13,13,1277333.0,Bangalore,Bangalore,1,0,8181096.0,8181096.0,8553953.0,8553953.0,0.0,100.0,2443.0,2836.0,943.0,1095.0,1908.0,2412.0,1186.0,1499.0,77.275000,77.275000,77.996673,78.150000,12.325000,12.325000,13.333333,13.333333,77.703019,12.841733,1,Bengaluru,P,PPL,19.0,5104047.0,920.0,914.0,Asia/Kolkata,GeoNames spatial join with similar names only.,219,India,12.97,77.58,746.0,939.0,1166.0,1377.0,1615.0,2111.0,2812.0,3395.0,4036.0,4744.0,5567.0,6465.0,6787.0,7229.0,7967.0,8795.0,9719.0,None,3.7,Q1355,102030819,0,Bangalore,Bangalore,Bangalore,Bangalore,Bangalore,Бангалор,班加羅爾,None,بنغالور,বেঙ্গালুরু,Μπανγκαλόρ,बंगलौर,Bengaluru,Bengaluru,Bangalore,バンガロール,벵갈루루,Bangalore,Bengaluru,Bangalore,Bangalore,Bengaluru,4,1159151543,POINT (8633724.176 1456526.778)
7280,0,600,1,Admin-1 capital,Mumbai,Bombay,None,0,Mumbai,0.0,None,1.0,1,India,IND,India,IND,Maharashtra,IN,None,19.016990,72.856989,0.0,0,None,18978000,12691836,12426085,14,14,1275339.0,Mumbai,Mumbai,1,0,12814908.0,20149761.0,20149761.0,20149761.0,20149761.0,300.0,442.0,1479.0,171.0,571.0,244.0,1021.0,152.0,634.0,72.758333,72.775000,72.983154,73.266667,18.891667,18.891667,19.308333,19.491667,72.959776,19.189154,0,Mumbai,P,PPLA,16.0,12691836.0,0.0,12.0,Asia/Kolkata,GeoNames match general.,253,India,19.07,72.82,2857.0,3432.0,4060.0,4854.0,5811.0,7082.0,8658.0,10341.0,12308.0,14111.0,16086.0,18202.0,18978.0,20072.0,21946.0,24051.0,26385.0,Bombay,1.7,Q1156,102030609,0,Mumbai,Mumbai,Bombay,Bombay,Bombaim,Мумбаи,孟买,None,مومباي,মুম্বই,Μουμπάι,मुम्बई,Mumbai,Mumbai,Mumbai,ムンバイ,뭄바이,Bombay,Mumbaj,Bombay,Mumbai,Mumbai,4,1159151611,POINT (8110186.337 2157165.477)
7283,0,600,1,Admin-1 capital,Kolkata,Calcutta,None,0,Kolkata,0.0,None,0.0,1,India,IND,India,IND,West Bengal,IN,None,22.494969,88.324676,4.0,1,Name changed. Changed scale rank.,14787000,4631392,7783716,14,12,1275004.0,Kolkata,Calcutta,1,0,8143162.0,18577087.0,48715672.0,87652060.0,0.0,100.0,2490.0,53331.0,962.0,20591.0,0.0,35493.0,0.0,22054.0,85.483333,87.714444,88.850000,89.455426,19.866667,22.056849,22.575491,25.259961,88.040398,22.616509,1,Calcutta,P,PPLA,28.0,4631392.0,0.0,16.0,Asia/Kolkata,GeoNames match general.,245,India,22.54,88.33,4513.0,5055.0,5652.0,6261.0,6926.0,7888.0,9030.0,9946.0,10890.0,11924.0,13058.0,14282.0,14787.0,15577.0,17039.0,18707.0,20560.0,Calcutta,3.7,Q1348,102030585,0,Kolkata,Kalkutta,Calcuta,Calcutta,Calcutá,Калькутта,加尔各答,None,كلكتا,কলকাতা,Καλκούτα,कोलकाता,Kalkutta,Kolkata,Calcutta,コルカタ,콜카타,Calcutta,Kolkata,Calcutta,Kalküta,Kolkata,4,1159151617,POINT (9832041.307 2571291.354)

In [ ]:
basemap = India.plot(column='CONTINENT', cmap='cool')
Indian_cities.plot(ax=basemap, marker='o', color='red', markersize=2);

In [18]:
# add buffer of 50 KM to Indian_cities point
# buffered_cities =Indian_cities.buffer(50)
buffered_cities = Indian_cities.copy()
buffered_cities['geometry'] = buffered_cities.buffer(50000)

In [ ]:
basemap = India.plot(column='CONTINENT', cmap='cool')
buffered_cities.plot(ax=basemap,  color='red');

In [ ]:
rural_area = gpd.overlay(India, buffered_cities, how='difference').plot()
rural_area.plot()

In [125]:
## 4. Creating Interactive Map using ipyleaflet

In [137]:
m = Map(center=(27,71), zoom = 3, basemap= basemaps.Esri.WorldTopoMap)

Indian_data  = GeoData(geo_dataframe = Indian_cities,
    style={'color': 'black', 'radius':8, 'fillColor': '#3366cc', 'opacity':0.5, 'weight':1.9, 'dashArray':'2', 'fillOpacity':0.6},
    hover_style={'fillColor': 'red' , 'fillOpacity': 0.2},
    point_style={'radius': 5, 'color': 'red', 'fillOpacity': 0.8, 'fillColor': 'blue', 'weight': 3},
    name = 'Release')
m.add_layer(Indian_data)
m

Map(center=[27, 71], controls=(ZoomControl(options=['position', 'zoom_in_text', 'zoom_in_title', 'zoom_out_tex…

In [138]:
Indian_cities.crs

<Projected CRS: EPSG:3857>
Name: WGS 84 / Pseudo-Mercator
Axis Info [cartesian]:
- X[east]: Easting (metre)
- Y[north]: Northing (metre)
Area of Use:
- name: World between 85.06°S and 85.06°N.
- bounds: (-180.0, -85.06, 180.0, 85.06)
Coordinate Operation:
- name: Popular Visualisation Pseudo-Mercator
- method: Popular Visualisation Pseudo Mercator
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich